# Generated by Django 5.1 on 2024-10-15 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_profile_pics_profile_pictures'),
        ('App', '0007_alter_cart_grand_total_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('address', models.CharField()),
                ('user_token', models.IntegerField()),
                ('delivery_token', models.IntegerField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.cust_register')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_id', models.CharField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.cust_register')),
            ],
        ),
    ]
