# Generated by Django 5.1 on 2024-10-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_details',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pets',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
