# Generated by Django 5.1 on 2024-10-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_cust_register_city_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pics',
            name='profile_pic',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
