# Generated by Django 5.1 on 2024-10-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_profile_pics_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_pics',
            new_name='Profile_pictures',
        ),
    ]
